apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "runai-model-downloader.fullname" . }}-pvc
  labels:
    {{- include "runai-model-downloader.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
