apiVersion: v2
name: runai-model-downloader
description: Helm Chart pour télécharger un modèle HuggingFace (ou miroir interne), dimensionner automatiquement un PV/PVC et créer un Run:ai Data Volume via API Run:ai.
type: application
version: 1.0.0
appVersion: "1.0.0"
