{{- if and (not .Values.postgres.existingSecret) .Values.postgres.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-backup.fullname" . }}-pg-secret
  labels:
    {{- include "postgres-backup.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
{{- end }}
---
{{- if and (not .Values.s3.existingSecret) .Values.s3.accessKeyId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-backup.fullname" . }}-s3-secret
  labels:
    {{- include "postgres-backup.labels" . | nindent 4 }}
type: Opaque
stringData:
  aws-access-key-id: {{ .Values.s3.accessKeyId | quote }}
  aws-secret-access-key: {{ .Values.s3.secretAccessKey | quote }}
{{- end }}
