apiVersion: v2
name: postgres-backup
description: Helm Chart pour le backup à chaud (pg_dump) de PostgreSQL sur OpenShift avec streaming vers un bucket S3 compatible.
type: application
version: 1.0.0
appVersion: "16-alpine"
